server:
  port: 8080
  
spring:
  datasource: #数据库连接配置
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/recruit?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: 123456
    
  http:
    encoding:
       force: true
       charset: utf-8
    
  mail:
    host: smtp.qq.cpm
    username: 2675657329@qq.com
    password: hvnktgkexeghebhj
    port: 465
    portocol: smtp
    properties:
       mail:
          smtp:
             auth: true
             sll: 
                enable: true
    
#mybatis配置
mybatis:
  mapper-locations: mapper/*Mapper.xml
  type-aliases-package: com.dq.springboot_recruit.entity #要扫描的启用别名的类所在的包
  
logging:
   level:
      com.dq.springboot_recruit.mapper: debug
   file:
     path: D:\Java\springboot_recruit-master\log
